### ISSUE TITLE
set doesn't expand regex 

### ISSUE THREAD

**Issue by X-Ryl669** [stalwartlabs/sieve#8]
Example sieve script:
```
require ["variables", "envelope", "regex"];
if envelope :regex "to" "alias\.([^.]+)@(.+)$") {
    set "to" "${2}";
    reject "Error ${to}";
}
```

Expected `bob` for an envelope.to set to `alias.bob@domain`. Got `{$2}` instead

**Side note:** It works if going through a `:replace` like `set :replace "." "" "to" "{$2}";`

**Comment by X-Ryl669** [comment]
Linking the other issue here for reference https://github.com/stalwartlabs/mail-server/issues/611

**Comment by mdecimus** [comment]
This can't be reproduced, see [this commit](https://github.com/stalwartlabs/sieve/commit/82ef6a3dac43608fe93d8c24d319d6ba189b49b9).
