### ISSUE TITLE
fileinto doesn't expand variable nor regex

### ISSUE THREAD

**Issue by X-Ryl669** [stalwartlabs/sieve#9]
Example sieve script:
```
require ["variables", "envelope", "regex", "fileinto", "mailboxid", "mailbox", "copy"];

if envelope :regex "to" "^([^+]+)\\+([^+]+)@(.+)$" {
   fileinto :create "{$2}";
}
```

Expecting fileinto to store mail in the subaddress (for example `bob` if initial to was "alice+bob@charlie"). Got the mail filed into "{$2}" instead.

**Side note**: This doesn't work either
```
require ["variables", "envelope", "regex", "fileinto", "mailboxid", "mailbox", "copy"];

if envelope :regex "to" "^([^+]+)\\+([^+]+)@(.+)$" {
   set :replace "." "" "folder" "${2}";
   fileinto :create "{$folder}";
}
```
This files the mail into a folder called "{$folder}" and not the value of the variable (which is correct).

**Comment by X-Ryl669** [comment]
Linking the other issue here for reference https://github.com/stalwartlabs/mail-server/issues/611

**Comment by mdecimus** [comment]
Variables are expanded using `${variable}` and not `{$variable}`. Your above example should be:

```sieve
require ["variables", "envelope", "regex", "fileinto", "mailboxid", "mailbox", "copy"];

if envelope :regex "to" "^([^+]+)\\+([^+]+)@(.+)$" {
   fileinto :create "${2}";
}
```
